version: "3.3"

services:
  mysql:
    container_name: mysql
    image: mysql:8
    expose:
      - "3306"
    environment:
      MYSQL_DATABASE: ${MYSQL_DB}
      MYSQL_HOST: ${MYSQL_HOST}
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    command: 
      - --character-set-server=utf8mb4
      - --collation-server=utf8mb4_unicode_ci

    volumes:
      - ./db/data:/var/lib/mysql
      - ./db/conf.d:/etc/mysql/conf.d
    networks:
      - mynetwork
    healthcheck:
      test: ["CMD-SHELL", "ping", "-h", "localhost"]
      interval: 30s
      timeout: 30s
      retries: 5

  web:
    build: 
      context: .
      dockerfile: Dockerfile
    command: python manage.py migrate && python manage.py collectstatic --noinput && python manage.py runserver 0.0.0.0:8000 
    expose:
      - "8000"
    ports:
      - "8000:8000"
    restart: always
    volumes:
      - ./app:/app
      - static_volume:/app/staticfiles/
    links:
      - mysql:mysql
    depends_on:
      - mysql
    networks:
      - mynetwork

networks:
  mynetwork:

volumes:
  static_volume: